### PR TITLE
Allowed keys can be even simple.

### PR DESCRIPTION
**Pull request by gartz**

### CODE REVIEW

**Comment by bcinarli** [comment]
The condition formatting is same but not working as expected.

See the [sample](http://jsfiddle.net/fjeb47g3/)

**Comment by bcinarli** [comment]
Sorry :( it is also working, I've added wrong class name for binding

Working version: http://jsfiddle.net/fjeb47g3/1/

**Comment by gartz** [comment]
screen shot 2015-02-18 at 10 24 48 pm

you tell me buddy, the logic is the same and the return from the function are the same.

you also can do this:

``` javascript
return !(e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57));
```

**Comment by bcinarli** [comment]
Yep, with the sleepy eyes, I defined the class in input as `numeric-shorter` and in the jQuery as `numeric_shorter` so it didn't work (^.^)

**Comment by gartz** [comment]
go sleep programmer, you are drunk :P

tumblr_md0nnbvhzs1qg0zdzo1_500

**Comment by bcinarli** [comment]
8 am in İstanbul, our day just started with heavy snow. Conflicted your PR and merged it again :/

**Comment by gartz** [comment]
here it's 11:15pm San Francisco, I'm going to sleep. Istanbul is super beautiful lucky of you :)

Before I go, I will link a pearl from a friend: https://github.com/Expensify/Segmented-Control also known  as input radio with CSS :P

**Comment by bcinarli** [comment]
Thanks @gartz, for your thought and for your contribution. Now checking `that` pearl :)

I like İstanbul except its traffic :/

**Pull request closed without merging**
