### PR TITLE
Make redundancy example even better

### PR DESCRIPTION
**Pull request by scriptype**
When removing a `className` from a set of elements, filtering it into
the elements that _actually_ have that className will greatly increase code performance.

Apply `do one thing in one line` rule.

### CODE REVIEW

**Comment by scriptype** [comment]
Changes I made to first example will make code don't work because we don't get all `li`s before finding the `"#" + slug`.

``` javascript
$(".leftMenu").find('li.active')
    .removeClass('active')
    .filter("#" + slug)
    .addClass('active');
```

Quick fix for this:

``` javascript
var $leftMenu = $(".leftMenu")

$leftMenu.find('li.active')
    .removeClass('active')

$leftMenu.find("#" + slug)
    .addClass('active');
```

So we
- can get only elements that are actually `.active`,
- remove `.active` from them,
- get back to list root,
- find specific element we want to get,
- add class `.active` to it.

**Comment by bcinarli** [comment]
Just made a quick/simple jsPerf test http://jsperf.com/selectors-and-add-remove-class

Single line code has better performance :) in Chrome
Remove Selected version has better performance in Safari
Remove Selected One Liner has better performance in IE11

so, which is suits your coding taste, is better.

**Comment by scriptype** [comment]
I made a revision based on it. This time there are an extensive number of `li`s:

http://jsperf.com/selectors-and-add-remove-class/2

As number of elements to query grows, filtering method makes a clear difference. Writing chain methods in new lines is, I think, only a matter of code-style preference and has an ignorable downside effect on performance, as can be seen in both tests.

**Comment by bcinarli** [comment]
Yep, in extreme cases, selecting with class has better performance.

Best: 

``` javascript
$("#menu").find('li.active').removeClass('active').end().find('.selected').addClass('active');
```

and

``` javascript
$("#menu").find('li.active')
                  .removeClass('active')
                  .end()
                  .find('.selected')
                  .addClass('active');
```

**Comment by bcinarli** [comment]
Thanks for the suggestion, revised the solution as

``` javascript
$(".leftMenu").find('.active').removeClass('active').end().find("#" + slug).addClass('active');
```

**Pull request closed without merging**
